### ISSUE TITLE
Inconsistencies in use of styles

### ISSUE THREAD

**Issue by asbisen** [sglyon/PlotlyBase.jl#15]
I believe we should explicitly add `attr(margin())` to each predefined style. The issue I am experiencing is that because of `gadfly_dark`'s style has a little too tight margin it's not properly showing title or labels. 

Additionally any subsequent plot with different styles also gets messed up because `gadfly_dark` changes the default once used. See below

`:fivethirtyeight` working fine 
![newplot](https://user-images.githubusercontent.com/5142211/47956749-dcde1400-df66-11e8-86f5-00491244263b.png)

`:gadfly_dark` used and shows improper margins
![newplot-2](https://user-images.githubusercontent.com/5142211/47956756-faab7900-df66-11e8-9900-f9c035bc1a4c.png)

subsequent `:fivethirtyeight` inherits the margins from `:gadfly_dark`
![newplot-3](https://user-images.githubusercontent.com/5142211/47956766-1282fd00-df67-11e8-9e42-2a450d47ed10.png)

**Comment by sglyon** [comment]
closed in #16
