### ISSUE TITLE
Configuration Options

### ISSUE THREAD

**Issue by EricForgy** [sglyon/PlotlyBase.jl#2]
Hi @sglyon 👋 

In plotly.js, there are actually four arguments to the `Plotly.plot` and `Plotly.newPlot` commands, i.e.

```js
Plotly.newPlot(graphdiv, data, layout, options)
```

The fourth argument constitutes configurations options:

https://plot.ly/javascript/configuration-options/

These include:

  - scrollZoom
  - editable
  - staticPlot
  - displayModeBar
  - linkText
  - showLink
  - displaylogo
  - modeBarButtonsToRemove

In addition to `data` and `layout`, it would be great if `options` was a part of PlotlyBase.jl. 

If you could give me a hint how to get started I could try adding it 🙏 😊

**Comment by sglyon** [comment]
Hey @EricForgy I think this is a great idea! It has long been on my todo list.

I think the `Plot` struct should have a `config` field.

I then think that our API methods for `Plot` (and `plot` in PlotlyJS.jl) can special case the `config` argument.

This `config` argument could accept one of two:

-  a `Union{Associative, PlotlyAttribute}`(I foresee myself using it with the `attributes` function).
- an instance of a `PlotConfig` object that has the items you listed above. 

(Sorry for the lack of structure here -- I'm thinking out loud and not being super organized before I hop on a flight)

I'm happy to do either. Maybe we could have the `config` field be an instance of `PlotConfig` and then coerce whatever people sent in to the `config` keyword arg to an instance of `PlotConfig`?

**Comment by sglyon** [comment]
As this is a feature that is relevant when _display_ing a plot, not when building the plot I decided to implement it over in PlotlyJS.jl, which handles the display side of things.

Thanks for the suggestion!
