### ISSUE TITLE
New DataFrames Version breaks Plotly

### ISSUE THREAD

**Issue by Rudi79** [sglyon/PlotlyBase.jl#34]
In DataFrames 0.22.0 the `by` function errors instead of giving a deprecation warning as in the previous version.
It is used in 
https://github.com/sglyon/PlotlyBase.jl/blob/c4c56ab95c3328cd5623b6f54b24e0bdab6730e9/src/dataframes_api.jl#L41

A quick fix would be to change
https://github.com/sglyon/PlotlyBase.jl/blob/c4c56ab95c3328cd5623b6f54b24e0bdab6730e9/src/dataframes_api.jl#L41-L44
to 
```julia
  _traces = map(dfg -> GenericTrace(dfg; kind=kind, name=_group_name(dfg, group), kwargs...), DataFrames.groupby(df, group))
  return GenericTrace[t for t in _traces]
```

**Comment by sglyon** [comment]
Would you be willing to make a pull request that implements the change?
