### ISSUE TITLE
`too long to load image` error when saving PDF

### ISSUE THREAD

**Issue by rasmushenningsson** [sglyon/PlotlyBase.jl#36]
If I run the following code to create a plot a save to PDF
```julia
using Plotly
N = 200000;
pl = plot([heatmap(;z=randn(10,10)), scatter(;x=10*rand(N),y=10*rand(N),mode="markers")]);
savefig(pl, "test.pdf")
```
I get the error message
> ERROR: LoadError: Transform failed with error code 525: too long to load image

It's easy to "fix", if I remove [this line in kaleido.jl](https://github.com/sglyon/PlotlyBase.jl/blob/c527a8ba9764b4c91910487534e3a4c1a0aacc2f/src/kaleido.jl#L100)
```julia
error("Transform failed with error code $code: $msg")
```
it actually works, the PDF was saved correctly!

But I'm not sure about the proper way to solve it.

1. Is it a bug in [Kaleido](https://github.com/plotly/Kaleido)?
2. Is it OK to ignore the error (show as a warning)?

**Comment by rasmushenningsson** [comment]
I also created an issue in Kaleido: https://github.com/plotly/Kaleido/issues/60

**Comment by sglyon** [comment]
Kaleido support moved to PlotlyJS.jl -- if this is still an ongoing issue, please re-open there. 

Thanks!
