### ISSUE TITLE
Dataframes API broken

### ISSUE THREAD

**Issue by Rudi79** [sglyon/PlotlyBase.jl#48]
The following example from the documentation does not work anymore (tested with DataFrames 1.0.1 and PlotlyJS 0.14.1)
```julia
using RDatasets,PlotlyJS
iris = dataset("datasets", "iris")
p = Plot(iris, x=:SepalLength, y=:SepalWidth, mode="markers", marker_size=8, group=:Species)
``` 
I have added a pr to fix the problem: #47

**Comment by sglyon** [comment]
Merged!
