### ISSUE TITLE
Clearing all traces

### ISSUE THREAD

**Issue by cstjean** [sglyon/PlotlyBase.jl#5]
I'd like to update a plot, but in my case, it's easier to wipe all traces, and redraw the plot. Is there an easy way to do that? [Plotly.deletetraces](https://plot.ly/javascript/plotlyjs-function-reference/#plotlydeletetraces) does part of the job, but it needs to be called individually for each trace.

**Comment by sglyon** [comment]
Could `deletetraces!(p::Plot, 1:length(p.data)...)` do work?

**Comment by cstjean** [comment]
It does the first time, but after the `deletetraces!` call, `length(p.data)` didn't change. It seems that `deletetraces!` does not keep `p.data` updated?

**Comment by cstjean** [comment]
Oh wait, nevermind, I was using `0:length(p.data)-1`, and that had some weird behaviour, but it seems that your line works. Thank you.
