### ISSUE TITLE
Make it possible to work without starting kaleido

### ISSUE THREAD

**Issue by waralex** [sglyon/PlotlyBase.jl#52]
The launch of kaleido (`_start_kaleido_process` call) takes quite a long time, and it is not always necessary. For example, `Dash.jl` uses `PlotlyBase` only to generate json for `PlotlyGraph` objects. But at the same time, the launch of kaledio takes 90 percent of the time of `using Dash` (about 2.5 seconds on my laptop).

It would be really great if it could be avoided.
The options that I see are:
- take out the kaleido to the  `PlotlyJS.jl`
- run it in lazy mode on demand
- Make a separate package for working with plotly json

Perhaps there are other options

**Comment by alexcjohnson** [comment]
Nice find @waralex - on the Python side we do two things that look different from this:
(1) Kaleido is an optional dependency of plotly.py; if we don't find it when starting up, that functionality is disabled. We've discussed making a core package with minimal dependencies, and a "batteries included" package that installs the core and all the optional dependencies. Most users would then use the full package and everything would work, but those with more specific needs could streamline their installation and imports.
(2) Kaleido is lazy in starting its process.

**Comment by sglyon** [comment]
Some timing results:

### Without auto-start kaleido, PlotlyBase needs to precompile

```
julia> @time using PlotlyBase  # precompile, without auto start kaleido
[ Info: Precompiling PlotlyBase [a03496cd-edff-5a9b-9e67-9cda94a718b5]
  2.160184 seconds (2.57 M allocations: 153.969 MiB, 1.24% gc time, 20.47% compilation time)

julia> p = Plot(rand(3, 2));

julia> @time savefig(p, expanduser("~/deleteme.png"));  # first save, without already running kaleido
  1.963934 seconds (3.58 M allocations: 194.157 MiB, 2.71% gc time)

julia> @time savefig(p, expanduser("~/deleteme.png"));  # second save, without already running kaleido
  0.048885 seconds (1.11 k allocations: 285.953 KiB)
```

### Without auto-start kaleido, PlotlyBase already precompiled

```
julia> @time using PlotlyBase  # already compiled, without auto start kaleido
  0.523687 seconds (1.11 M allocations: 68.566 MiB)

julia> p = Plot(rand(3, 2));

julia> @time savefig(p, expanduser("~/deleteme.png"));  # first save, without already running kaleido
  1.978416 seconds (3.60 M allocations: 195.150 MiB, 2.41% gc time)

julia> @time savefig(p, expanduser("~/deleteme.png")) ; # second save, without already running kaleido
  0.048573 seconds (1.02 k allocations: 278.781 KiB)
```

### With auto-start kaleido, PlotlyBase needs to precompile

```
julia> @time using PlotlyBase  # precompile, auto start kaleido
[ Info: Precompiling PlotlyBase [a03496cd-edff-5a9b-9e67-9cda94a718b5]
  3.367491 seconds (3.89 M allocations: 216.112 MiB, 1.45% gc time, 13.03% compilation time)

julia> p = Plot(rand(3, 2));

julia> @time savefig(p, expanduser("~/deleteme.png"));  # first save, with already running kaleido
  0.814506 seconds (2.07 M allocations: 121.842 MiB, 4.66% gc time)

julia> @time savefig(p, expanduser("~/deleteme.png"));  # second save, without already running kaleido
  0.059548 seconds (1.05 k allocations: 280.875 KiB)
```

### With auto-start kaleido, PlotlyBase already precompiled

```
julia> @time using PlotlyBase  # already precompiled, auto start kaleido
  1.598991 seconds (2.44 M allocations: 131.717 MiB, 2.19% gc time)

julia> p = Plot(rand(3, 2));

julia> @time savefig(p, expanduser("~/deleteme.png"));  # first save, with already running kaleido
  0.862816 seconds (2.07 M allocations: 121.848 MiB, 4.35% gc time)

julia> @time savefig(p, expanduser("~/deleteme.png"));  # second save, without already running kaleido
  0.050356 seconds (1.07 k allocations: 283.844 KiB)
```

### With auto-start kaleido (async), PlotlyBase needs to be precompiled

```
julia> @time using PlotlyBase  # precompile, async auto start kaleido
[ Info: Precompiling PlotlyBase [a03496cd-edff-5a9b-9e67-9cda94a718b5]
  2.384080 seconds (3.90 M allocations: 217.672 MiB, 2.18% gc time, 18.61% compilation time)

julia> p = Plot(rand(3, 2));

julia> @time savefig(p, expanduser("~/deleteme.png"));  # first save, with already running kaleido -- async
  0.959456 seconds (2.06 M allocations: 121.326 MiB, 13.34% gc time)

julia> @time savefig(p, expanduser("~/deleteme.png"));  # second save, with already running kaleido -- async
  0.053279 seconds (1.01 k allocations: 276.703 KiB)
```

### With autto-start kaleido (async), PlotlyBase already precompiled

```
julia> @time using PlotlyBase  # already precompiled, async auto start kaleido
  0.717933 seconds (2.45 M allocations: 133.282 MiB, 4.54% gc time)

julia> p = Plot(rand(3, 2));

julia> @time savefig(p, expanduser("~/deleteme.png"));  # first save, with already running kaleido -- async
  0.935251 seconds (2.06 M allocations: 121.204 MiB, 13.78% gc time)

julia> @time savefig(p, expanduser("~/deleteme.png"));  # second save, with already running kaleido -- async
  0.049776 seconds (976 allocations: 275.484 KiB)
```
- - - 

From what I see here, my vote would be to leave the auto start Kaleido, but to have it launch async. 

Any objections?

**Comment by sglyon** [comment]
One more set of timing:

```

❯ time julia --startup-file=no --project=@. -e 'using PlotlyBase; p = Plot(rand(3,2)); savefig(p, expanduser("~/deleteme.png"))'  # to precompile -- async start kaleido        
julia --startup-file=no --project=@. -e   3.65s user 0.30s system 89% cpu 4.405 total

❯ time julia --startup-file=no --project=@. -e 'using PlotlyBase; p = Plot(rand(3,2)); savefig(p, expanduser("~/deleteme.png"))'  # already precompiled -- async start kaleido
julia --startup-file=no --project=@. -e   2.11s user 0.13s system 82% cpu 2.703 total

❯ time julia --startup-file=no --project=@. -e 'using PlotlyBase; p = Plot(rand(3,2)); savefig(p, expanduser("~/deleteme.png"))'  # to precompile -- start kaleido      
julia --startup-file=no --project=@. -e   3.62s user 0.19s system 86% cpu 4.422 total

❯ time julia --startup-file=no --project=@. -e 'using PlotlyBase; p = Plot(rand(3,2)); savefig(p, expanduser("~/deleteme.png"))'  # already precompiled -- start kaleido
julia --startup-file=no --project=@. -e   2.06s user 0.10s system 75% cpu 2.838 total

❯ time julia --startup-file=no --project=@. -e 'using PlotlyBase; p = Plot(rand(3,2)); savefig(p, expanduser("~/deleteme.png"))'  # to precompile -- no start kaleido   
julia --startup-file=no --project=@. -e   3.44s user 0.18s system 85% cpu 4.229 total

❯ time julia --startup-file=no --project=@. -e 'using PlotlyBase; p = Plot(rand(3,2)); savefig(p, expanduser("~/deleteme.png"))'  # already precompiled -- no start kaleido
julia --startup-file=no --project=@. -e   2.06s user 0.09s system 77% cpu 2.759 total
```

If we are running a script to load, plot, savefig it doesn't seem to matter which option we choose

**Comment by waralex** [comment]
@sglyon  Are you sure that it is necessary in `PlotlyBase`? This is a fairly high level functionality more related to the display than to the model and it seems to me that it should be taken out to `PotlyJS` with `savefig` at all.

**Comment by sglyon** [comment]
It isn't necessary. I would be willing to move this over

**Comment by waralex** [comment]
The problem is not only in the launch time. By itself, starting a process that is most likely not needed by the user is not very good, IMHO.

**Comment by hhaensel** [comment]
I want to come back to this topic.

I suddenly realised that savefig was not working anymore and finally found out why.

While I can understand all the arguments above, I'm missing the possibility to save figures with a small footprint. Loading the full PlotlyJS with heavy dependencies like `WebIO` is worse than loading `Kaleido_jll` with `PlotlyBase`.

I'd propose to define an abstract type `AbstractPlot` with subtypes `Plot` and `SyncPlot` and to generate a package `PlotlySave` that defines savefig for `AbstractPlot`s.

I'd even propose to use FileIO and to define a new save method
```julia
import FileIO.save
function save(io, p:AbstractPlot) [...]
```
and keeping `savefig` and `savejson` for compatibility.

@sglyon What do you think?

**Comment by hhaensel** [comment]
I have published [PlotlySave.jl](https://github.com/hhaensel/PlotlySave) on my GitHub and created branches hh-abstractplot for my forks of `PlotlyBase` and `PlotlyJS`.
The tests run without errors for both `PlotlyBase` and `PlotlyJS`.
