### ISSUE TITLE
Missing `modeBarButtons` config option

### ISSUE THREAD

**Issue by etpinard** [sglyon/PlotlyBase.jl#60]
The new [`PlotConfig`](https://github.com/sglyon/PlotlyBase.jl/blob/078506c90fa9c1cda187d76faec7fc75f9b72522/src/plot_config.jl#L24-L40) type does not include the `modeBarButtons` config options from plotly.js:

https://github.com/plotly/plotly.js/blob/51eded41ac7433a9193fe0c21439dbc5f92b6dd6/src/plot_api/plot_config.js#L299-L308

Prior to https://github.com/sglyon/PlotlyBase.jl/pull/53, we could set it using the old `options` kwarg:

```jl
# add selection buttons which do not appear by default
# when graph only has mode="lines" traces
config = Dict(:modeBarButtons=>[["toImage"],
                               ["zoom2d", "pan2d", "select2d", "lasso2d"],
                               ["zoomIn2d", "zoomOut2d", "autoScale2d", "resetScale2d"],
                               ["toggleSpikelines", "hoverClosestCartesian", "hoverCompareCartesian"]]
PlotlyJS.plot(traces, layout; options=config)
```

Is this by design? If not, I can make a PR that adds `modeBarButtons`. 

Thanks!!

**Comment by sglyon** [comment]
Definitely not by design :(

Somehow I must have missed that one. A PR would be welcome
