### ISSUE TITLE
v0.8.2 broke layout setting of axes?

### ISSUE THREAD

**Issue by thchr** [sglyon/PlotlyBase.jl#63]
Using PlotlyJS.jl v0.18.3, and pinning PlotlyBase.jl to v0.8.1, I get the intended behavior for a plot from my package Brillouin.jl (example below), namely:
![image](https://user-images.githubusercontent.com/26799210/127885481-3e63c440-8190-4acd-a9f4-480f6a3aadab.png)

If I then pin PlotlyBase.jl to v0.8.2 or later, the "axis boxes" that were set in the layout via
```jl
Layout(
    xaxis=attr(showline=true, mirror=true, ...),
    yaxis=attr(showline=true, mirror="all", ...)
)
```
mysteriously vanish:
![image](https://user-images.githubusercontent.com/26799210/127886138-91f59e5d-90a4-4567-971c-518753f80553.png)

I'm not exactly sure what caused this?

<details>
<summary>Example code</summary>

Here's a not-so-minimal example (since it uses the package I mentioned; specifically, the layout is set [here](https://github.com/thchr/Brillouin.jl/blob/8fba6aff9ccf8e8556d22e62ee4084dd8f555cdb/src/requires/plotlyjs_dispersion.jl#L8-L26)):

```jl
using Brillouin, PlotlyJS
sgnum = 227
Rs = [[1,0,0], [0,1,0], [0,0,1]] # conventional direct basis
kp = irrfbz_path(sgnum, Rs)

kpi = interpolate(kp, 100)

function ϵ(k; γ::Real=1.0)
    kx = 2π*(-k[1]+k[2]+k[3])
    ky = 2π*(+k[1]-k[2]+k[3])
    kz = 2π*(+k[1]+k[2]-k[3])
    return 4γ * (cos(kx/2)*cos(ky/2) + cos(ky/2)*cos(kz/2) + cos(kz/2)*cos(kx/2))
end
band = ϵ.(kpi)

band1 = ϵ.(kpi)
band2 = 20 .- (1/2).*band1
P¹² = plot(kpi, [band1, band2])
```

</details>

**Comment by thchr** [comment]
Okay, I found out what the issue is more or less: it seems the default plotting template changes from v0.8.1 to v0.8.2 and in the new template, the default value of the `x/yaxis` `linecolor` attribute seems to be `white` rather than `black`.

We can check two small examples to see this:
```jl
using PlotlyJS
p1 = scatter(x=1:10, y=1:10)
plot(p1, Layout(xaxis=attr(showline=true, mirror="all"), yaxis=attr(showline=true, mirror="all")))
```
On PlotlyJS.jl v0.18.3, with different versions of PlotlyBase.jl, this gives:

| PlotlyBase v0.8.1 | PlotlyBase v0.8.2 |
|---|---|
| ![image](https://user-images.githubusercontent.com/26799210/127892162-a049725a-310e-4c07-9cc7-aab38a548b5e.png) | ![image](https://user-images.githubusercontent.com/26799210/127892464-cad69be5-d8a7-463c-b19f-d34c7112d69b.png) |

But if we add `showline="red"` to both `xaxis` and `yaxis`, then we can indeed see drawing of both:

| PlotlyBase v0.8.1 | PlotlyBase v0.8.2 |
|---|---|
| ![image](https://user-images.githubusercontent.com/26799210/127893192-343435e0-e6c6-46ee-8b12-70ee8717ecf4.png) | ![image](https://user-images.githubusercontent.com/26799210/127892998-1e68852a-6e90-4827-8816-4053b4214f3e.png)

I'll leave this issue open in case this change was not intended - but if it was, or if it is due to some downstream change, please feel free to close it!

**Comment by sglyon** [comment]
Thanks @thchr and sorry for the delay

I think you are right that this is another side effect of the default template changing.

Is there anything actionable or anything that needs to be fixed here?

**Comment by thchr** [comment]
No, I think we can close it now since I now understand that the template change was intentional.

**Comment by sglyon** [comment]
Thanks! And thank you also for patience as we work through these types of "growing pains":
