### ISSUE TITLE
JSON3 for AbstractTraces

### ISSUE THREAD

**Issue by hhaensel** [sglyon/PlotlyBase.jl#88]
`JSON3.write()` is not defined for AbstractTraces.

I propose to define
```julia
StructTypes.StructType(::Type{<:PlotlyBase.AbstractTrace}) = JSON3.RawType()
JSON3.rawbytes(trace::PlotlyBase.AbstractTrace) = codeunits(JSON.json(trace))
```

in analogy to `PlotlyBase.Plot` in json3.jl

**Comment by hhaensel** [comment]
This is useful for using PlotlyBase in Vue.js implementations, where the traces are stored in the data of the vue model.
We want to use it in [Stipple.jl](https://github.com/GenieFramework/Stipple.jl).
Although we have our own implementation of Plotly, people who are familiar with PlotlyBase ask for compatibility with their known interface. These two lines would make [Stipple compatible with PlotlyBase](https://github.com/GenieFramework/Stipple.jl/issues/86#issuecomment-1010833977).

**Comment by cwiese** [comment]
works great!   However, we need to add AbstractLayout. 

```
StructTypes.StructType(::Type{<:PlotlyBase.AbstractTrace}) = JSON3.RawType()
JSON3.rawbytes(trace::PlotlyBase.AbstractTrace) = codeunits(JSON.json(trace))

StructTypes.StructType(::Type{<:PlotlyBase.AbstractLayout}) = JSON3.RawType()
JSON3.rawbytes(trace::PlotlyBase.AbstractLayout) = codeunits(JSON.json(trace))
```

**Comment by hhaensel** [comment]
That was already added 😉

**Comment by sglyon** [comment]
SGTM! please propose a PR and I'll merge

**Comment by hhaensel** [comment]
It's already there 😉 
See above...

**Comment by hhaensel** [comment]
I also asked in the PR, whether including AbstractShapes as well.
Meanwhile I think, we may want to include all abstract types ...

**Comment by hhaensel** [comment]
Close. The respective PR is merged.
