### ISSUE TITLE
Quick fix (I promise)

### ISSUE THREAD

**Issue by ghuba** [sglyon/PlotlyBase.jl#9]
<img width="818" alt="screen shot 2018-09-27 at 8 20 40 am" src="https://user-images.githubusercontent.com/4511360/46156496-76126000-c22e-11e8-82dc-2fd564b2827d.png">

Julia v1.0 requires LinRange instead of linspace. Can this be changed?

**Comment by ghuba** [comment]
I created a PR in case that helps.

**Comment by sglyon** [comment]
Thank you
